### ISSUE TITLE
md5sums and filenames are swapped

### ISSUE THREAD

**Issue by manjunaths** [basveeling/pcam#1]
The md5sums given in the table on the main page are swapped. Here are the md5sums if we run the md5sum command

1571f514728f59376b705fc836ff4b63  camelyonpatch_level_2_split_train_x.h5.gz
35c2d7259d906cfc8143347bb8e05be7  camelyonpatch_level_2_split_train_y.h5.gz
d5b63470df7cfa627aeec8b9dc0c066e  camelyonpatch_level_2_split_valid_x.h5.gz
2b85f58b927af9964a4c15b8f7e8f179  camelyonpatch_level_2_split_valid_y.h5.gz
d8c2d60d490dbd479f8199bdfa0cf6ec  camelyonpatch_level_2_split_test_x.h5.gz
60a7035772fbdb7f34eb86d4420cf66a  camelyonpatch_level_2_split_test_y.h5.gz

Here is what is on the main page

1571f514728f59376b705fc836ff4b63 camelyonpatch_level_2_split_train_x.h5.gz
35c2d7259d906cfc8143347bb8e05be7 camelyonpatch_level_2_split_train_y.h5.gz
d8c2d60d490dbd479f8199bdfa0cf6ec camelyonpatch_level_2_split_valid_x.h5.gz
60a7035772fbdb7f34eb86d4420cf66a camelyonpatch_level_2_split_valid_y.h5.gz
d5b63470df7cfa627aeec8b9dc0c066e camelyonpatch_level_2_split_test_x.h5.gz
2b85f58b927af9964a4c15b8f7e8f179 camelyonpatch_level_2_split_test_y.h5.gz

Is this an error ?

**Comment by basveeling** [comment]
Hi there,

Thanks for the heads-up, that's probably an copy/paste mismatch on my part, your files should be correct. I'll push a fix soon!

**Comment by basveeling** [comment]
I'll track this under #2.
