### ISSUE TITLE
Dataset hosting

### ISSUE THREAD

**Issue by ieee8023** [basveeling/pcam#2]
Hello,

This dataset is great but the downloader didn't work.

I put this data on Academic Torrents: http://academictorrents.com/details/1561a180b11d4b746273b5ce46772ad36f1229b6

-Joseph

**Comment by basveeling** [comment]
Hi Joseph,

Thanks for uploading it there. I'm still looking for a good host that can provide direct links to the file for the download script. Google Drive unfortunately doesn't provide such links, and I don't have budget for a paid solution. Any tips (from anyone reading this) are welcome!

**Comment by ieee8023** [comment]
With Academic Torrents people donate hosting to host your files in an ad-hoc way. We also have a pure python BitTorrent API to download files that you can integrate into your scripts: https://github.com/academictorrents/at-python

https://zenodo.org/ and https://figshare.com/ provide free hosting for academic data.

**Comment by basveeling** [comment]
That's great, I like the idea of decentralized hosting. I'll see if I can implement the dataloader using this, although I'm slightly worried about overzealous firewalls blocking torrent-traffic. What's your take on that?

**Comment by ieee8023** [comment]
Academic Torrents exists as a US non-profit so people can complain about their university blocking legitimate content.

We also have webseed support. So the data can be on web servers as well as on BitTorrent. If BitTorrent is blocked most torrent clients will download from a web server instead. We have a way of managing these web seeds dynamically on the website so the uploader of the torrent can change the "backup hosting" locations.

**Comment by nom** [comment]
Thank you for the suggestions @ieee8023. 

Having an extra package dependency to download the dataset is perhaps not desirable though. Figshare's data limit is too low, but Zenodo supports up to 50gb and also direct links it seems.
