### ISSUE TITLE
Issue with downloading the data

### ISSUE THREAD

**Issue by ghada-soliman** [basveeling/pcam#3]
The server is unreachable and in turn cannot download the data. Thanks.

**Comment by basveeling** [comment]
Hi,

Thanks for letting us know. Right now we have two mirrors in place. One is at academic torrents, see https://github.com/basveeling/pcam/issues/2
The other is available on:
https://zenodo.org/record/1494286

Let me know if you have any problems with that!

Kind regards,

Bas
